# Numpy

In [10]:
import numpy as np

In [4]:
v1 = np.array([10,20,30])
print(v1)

v2 = np.array([[1,2,3],[5,6,7]])
print(v2)

v3 = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(v3)

[10 20 30]
[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [11]:
type(v3)

numpy.ndarray

In [5]:
a = np.zeros((1,2))# need an empty numpy array 1 row and 2 cols
print(a)
b = np.zeros((5,6))
print(b)

[[0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
c = np.full((2,3),12) # initiate a numpy arrayw with 2 rows 3 cols and all the items in it as 12
print(c)
d = np.full((5,5),55)
print(d)

[[12 12 12]
 [12 12 12]]
[[55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]]


In [21]:
e = np.arange(10,20) # array of all items from 10 to 20
print(e)

f = np.arange(10,50,5) # array of items with a gap of 5
print(f)

[10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45]


In [9]:
g = np.random.randint(1,100,3) # an array of 3 random values between 1 and 100
print(g)

[34 90 33]


In [20]:
np.random.randn()

-0.5131971978278772

In [21]:
np.random.randn(10)

array([-0.75484768,  2.74086319,  0.95184184, -0.24673092, -0.37986592,
        1.22365038, -0.06079853, -2.23765129,  0.65886943, -0.15999123])

In [17]:

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
h = np.array([[2,3,4],[4,5,6]]) # identify the shape
h
h.shape
h.shape = (3,2) # changing the r and col size
h
h.shape = (6,1)
h

array([[2],
       [3],
       [4],
       [4],
       [5],
       [6]])

In [41]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
n2 = np.array([40,70,60])

n3=np.vstack((n1,n2)) # stack 2 arrays vertically one after the other
n3
n3.shape

n4 = np.hstack((n1,n2))# stack 2 arrays horizontally one after the other
n4
n4.shape

n5 = np.column_stack((n1,n2)) # stack 2 arrays in columnwise 
n5
n5.shape

n1 = np.array([10,20,30])# stack 3 arrays vertically one after the other
n2 = np.array([40,50,60])
n3 = np.array([40,70,60])
nw = np.vstack((n1,n2,n3))
nw

(2, 3)

In [15]:
n1 = np.array([10,20,30,50,60])
n2 = np.array([40,50,60,70])

np.intersect1d(n1,n2) # common values in n1 and n2

np.setdiff1d(n1,n2) # uniques values in n1 that are not present  in n2

np.setdiff1d(n2,n1)# # uniques values in n12 that are not present in n1

array([40, 70])

In [22]:
np.sum([[1,2,3],[5,6,7]]) #sum of all item in array
l1=[10,40]
l2=[20,50]
np.sum([l1,l2])
np.sum([l1,l2],axis=0) # sum of rows
np.sum([l1,l2],axis=1)# sum of columns

120

In [29]:
n1 = [10,20,30] # basic scalar operations
n= np.array(n1)

n+1
n-1
n*2
n/2

array([ 5., 10., 15.])

In [33]:
n1 = [10,20,30]  # mean ,median,standard deviation
np.mean(n1)
np.median(n1)
np.std(n1)

8.16496580927726

In [17]:
v3 = np.array([[[1,2,3],[4,5,6],[6,7,8]]])
print(v3)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [18]:
v3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
v3[0][1]

array([4, 5, 6])

In [25]:
p = 'a'
print('my frined's place is in {}'.format('a'))

SyntaxError: unterminated string literal (detected at line 2) (2717974304.py, line 2)

In [27]:
t1=(1,2,'tuple',4)
t2=(5,6,7)

In [29]:
x = t2[t1[1]]

In [30]:
t3=t1+t2

In [35]:
t3=(t1,t2)
t3

((1, 2, 'tuple', 4), (5, 6, 7))

In [32]:
t3

((1, 2, 'tuple', 4), (5, 6, 7))

In [33]:
t3 = (list(t1),list(t2))

In [34]:
t3

([1, 2, 'tuple', 4], [5, 6, 7])

In [36]:
d={1:'python',2:[1,2,3]}

In [37]:
d[2].append(4)

In [38]:
x=d[0]

KeyError: 0

In [39]:
d["one"]=1

In [40]:
d={1:'python',2:[1,2,3]}

In [41]:
d.update({'one':2})